// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT161_B_PriAPI.Models;

public partial class TChatImage
{
    public int FChatImageId { get; set; }

    public int FChatId { get; set; }

    public string FImageData { get; set; }

    public virtual TMemberChat FChat { get; set; }

    public virtual ICollection<TMemberChat> TMemberChats { get; set; } = new List<TMemberChat>();
}