// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT161_B_PriAPI.Models;

public partial class TColor
{
    public int FColorId { get; set; }

    public string FColorName { get; set; }

    public virtual ICollection<TRtwproductDetail> TRtwproductDetails { get; set; } = new List<TRtwproductDetail>();
}