// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT161_B_PriAPI.Models;

public partial class TCondition
{
    public int FConditionsId { get; set; }

    public string FConditionsName { get; set; }

    public virtual ICollection<TRtwproduct> TRtwproducts { get; set; } = new List<TRtwproduct>();
}