// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT161_B_PriAPI.Models;

public partial class TCoupon
{
    public int FCouponCodeId { get; set; }

    public string FCouponCodeName { get; set; }

    public string CouponDescription { get; set; }

    public string FCouponCode { get; set; }

    public double FCouponDiscount { get; set; }

    public DateTime FCouponCreatday { get; set; }

    public DateTime? FCouponEndday { get; set; }

    public bool? FCouponState { get; set; }

    public int FCouponFrom { get; set; }

    public decimal? MinSellMoney { get; set; }

    public virtual TUser FCouponFromNavigation { get; set; }

    public virtual ICollection<TCouponRedemption> TCouponRedemptions { get; set; } = new List<TCouponRedemption>();

    public virtual ICollection<TRtworder> TRtworders { get; set; } = new List<TRtworder>();
}