// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT161_B_PriAPI.Models;

public partial class TFriend
{
    public int FInvitationId { get; set; }

    public int FUserId { get; set; }

    public int FFriendUserId { get; set; }

    public DateTime FInvitationTime { get; set; }

    public virtual TUser FFriendUser { get; set; }

    public virtual TUser FUser { get; set; }
}