// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT161_B_PriAPI.Models;

public partial class TLoginRecord
{
    public int FLoginRecordId { get; set; }

    public int FUserId { get; set; }

    public string FLoginIp { get; set; }

    public DateTime FLoginTime { get; set; }

    public byte FLoginState { get; set; }

    public virtual TUser FUser { get; set; }
}