// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT161_B_PriAPI.Models;

public partial class TMemberChat
{
    public int FChatId { get; set; }

    public int FSenderId { get; set; }

    public int FReceiverId { get; set; }

    public int? FChatImageId { get; set; }

    public DateTime? FSendTime { get; set; }

    public string FMessage { get; set; }
    public bool FReport { get; set; }

    public virtual TChatImage FChatImage { get; set; }

    public virtual TUser FReceiver { get; set; }

    public virtual TUser FSender { get; set; }

    public virtual ICollection<TChatImage> TChatImages { get; set; } = new List<TChatImage>();
}