// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT161_B_PriAPI.Models;

public partial class TNotifyType
{
    public int FNotifyTypeId { get; set; }

    public string FNotifyType { get; set; }

    public virtual ICollection<TRtwnotify> TRtwnotifies { get; set; } = new List<TRtwnotify>();
}