// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT161_B_PriAPI.Models;

public partial class TPart
{
    public int FPartId { get; set; }

    public string FPartName { get; set; }

    public virtual ICollection<TRtwproduct> TRtwproducts { get; set; } = new List<TRtwproduct>();

    public virtual ICollection<TTag> TTags { get; set; } = new List<TTag>();
}