// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT161_B_PriAPI.Models;

public partial class TRtwshoppingCart
{
    public int FShoppingCartId { get; set; }

    public int? FUserId { get; set; }

    public int? FProductDetailId { get; set; }

    public int? FQty { get; set; }

    public DateOnly? FAddTime { get; set; }

    public virtual TRtwproductDetail FProductDetail { get; set; }

    public virtual TUser FUser { get; set; }
}