// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT161_B_PriAPI.Models;

public partial class TRtwproductDetail
{
    public int FProductDetailId { get; set; }

    public int? FProductId { get; set; }

    public int? FColorId { get; set; }

    public int? FSizeId { get; set; }

    public int FQty { get; set; }

    public int? FProductImageId { get; set; }

    public virtual TColor FColor { get; set; }

    public virtual TRtwproduct FProduct { get; set; }

    public virtual TRtwproductImage FProductImage { get; set; }

    public virtual TSize FSize { get; set; }

    public virtual ICollection<TRtworderDetail> TRtworderDetails { get; set; } = new List<TRtworderDetail>();

    public virtual ICollection<TRtwshoppingCart> TRtwshoppingCarts { get; set; } = new List<TRtwshoppingCart>();
}