// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT161_B_PriAPI.Models;

public partial class TRtwcomment
{
    public int FCommentId { get; set; }

	public int? FSellerId { get; set; }

	public int? FUserId { get; set; }

    public double? FScore { get; set; }

    public string FComment { get; set; }

    public DateOnly? FCommentDate { get; set; }

    public bool? AnonymousUser { get; set; }

    public string FSellerReply { get; set; }

	public virtual TUser FUser { get; set; }
}