// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT161_B_PriAPI.Models;

public partial class TRtwproduct
{
    public int FProductId { get; set; }

    public string FProductName { get; set; }

    public string FGender { get; set; }

    public int FPartId { get; set; }

    public int FTagId { get; set; }

    public int? FConditionsId { get; set; }

    public string FProductIllustrate { get; set; }

    public decimal FOriginPrice { get; set; }

    public int FUserId { get; set; }

    public bool? Fstate { get; set; }

    public virtual TCondition FConditions { get; set; }

    public virtual TPart FPart { get; set; }

    public virtual TTag FTag { get; set; }

    public virtual TUser FUser { get; set; }

    public virtual ICollection<TRtwproductDetail> TRtwproductDetails { get; set; } = new List<TRtwproductDetail>();
}