// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT161_B_PriAPI.Models;

public partial class TSendNotify
{
    public int FSendNotifyId { get; set; }

    public int FNotifyId { get; set; }

    public int? FUserId { get; set; }

    public string FNotify { get; set; }

    public bool? FIsNotRead { get; set; }

    public DateTime? FSendTime { get; set; }

    public virtual TRtwnotify FNotifyNavigation { get; set; }
}