// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT161_B_PriAPI.Models;

public partial class TShipMethod
{
    public int FShipMethodId { get; set; }

    public string FShipMethod { get; set; }

    public string FNeedTime { get; set; }

    public virtual ICollection<TRtworder> TRtworders { get; set; } = new List<TRtworder>();
}