// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT161_B_PriAPI.Models;

public partial class TUserTag
{
    public int FUserTagId { get; set; }

    public int FUserId { get; set; }

    public int FTagId { get; set; }

    public byte FTagNotification { get; set; }

    public virtual TTag FTag { get; set; }

    public virtual TUser FUser { get; set; }
}