// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT161_B_PriAPI.Models;

public partial class TUser
{
    public int FUserId { get; set; }

    public string FName { get; set; }

    public string FGender { get; set; }

    public DateTime? FBirthDate { get; set; }

    public string FAddress { get; set; }

    public int FUserLevel { get; set; }

    public string FInvitationCode { get; set; }

    public DateTime FRegistrationTime { get; set; }

    public DateTime FUpdatedTime { get; set; }

    public byte FUserIsSeller { get; set; }

    public string FProfileImage { get; set; }

    public virtual ICollection<AspNetUser> AspNetUsers { get; set; } = new List<AspNetUser>();

    public virtual ICollection<TCouponRedemption> TCouponRedemptions { get; set; } = new List<TCouponRedemption>();

    public virtual ICollection<TCoupon> TCoupons { get; set; } = new List<TCoupon>();

    public virtual ICollection<TFriend> TFriendFFriendUsers { get; set; } = new List<TFriend>();

    public virtual ICollection<TFriend> TFriendFUsers { get; set; } = new List<TFriend>();

    public virtual ICollection<TLoginRecord> TLoginRecords { get; set; } = new List<TLoginRecord>();

    public virtual ICollection<TMemberChat> TMemberChatFReceivers { get; set; } = new List<TMemberChat>();

    public virtual ICollection<TMemberChat> TMemberChatFSenders { get; set; } = new List<TMemberChat>();

    public virtual ICollection<TRtwcomment> TRtwcomments { get; set; } = new List<TRtwcomment>();

	


	public virtual ICollection<TRtwnotify> TRtwnotifies { get; set; } = new List<TRtwnotify>();

    public virtual ICollection<TRtworder> TRtworders { get; set; } = new List<TRtworder>();

    public virtual ICollection<TRtwproduct> TRtwproducts { get; set; } = new List<TRtwproduct>();

    public virtual ICollection<TRtwshoppingCart> TRtwshoppingCarts { get; set; } = new List<TRtwshoppingCart>();

    public virtual ICollection<TUserTag> TUserTags { get; set; } = new List<TUserTag>();
}